export enum ExceptionTypes {
  UNAUTHORIZED = "Unauthorized Error",
  JOB_FETCH_ERROR = "Job Fetch Error",
  S3_BUCKET_ERROR = "S3Bucket Error",
  JOB_UPDATE_ERROR = "Job Update Error",
  JOB_CREATE_ERROR = "Job Create Error",
  JOB_DELETE_ERROR = "Job Delete Error",
  AUTHENTICATION = "Authentication Error",
  EMAIL_DISPATCH_ERROR = "Email Dispatch Error",
  CLIENT_FETCH_ERROR = "Client Fetch Error",
  CLIENT_DELETE_ERROR = "Client Delete Error",
  CLIENT_EXPORT_ERROR = "Client Export Error",
  CLIENT_UPDATE_ERROR = "Client Update Error",
  CURRENCY_FETCH_ERROR = "Curreny Fetch Error",
  EMPLOYEE_FETCH_ERROR = "Employee Fetch Error",
  INDUSTRY_FETCH_ERROR = "Industry Fetch Error",
  DOCUMENT_FETCH_ERROR = "Document Fetch Error",

  CLIENT_CREATE_ERROR = "Client Creation Error",
  WAITLIST_FETCH_ERROR = "Waitlist Fetch Error",
  WAITLIST_CREATE_ERROR = "Waitlist Create Error",
  WAITLIST_DELETE_ERROR = "Waitlist Delete Error",
  DOCUMENT_CREATE_ERROR = "Document Create Error",
  DOCUMENT_DELETE_ERROR = "Document Delete Error",
  DOCUMENT_UPDATE_ERROR = "Document Update Error",
  INTERNAL_SERVER_ERROR = "Internal Server Error",
  FIREBASE_UPLOAD_ERROR = "Firebase Upload Error",
  EMPLOYEE_DELETE_ERROR = "Employee Delete Error",
  EMPLOYEE_CREATE_ERROR = "Employee Creation Error",
  EMPLOYEE_UDPATE_ERROR = "Employee Creation Error",
  INTEGRATION_FETCH_ERROR = "Integration Fetch Error",
  JOB_POSTING_FETCH_ERROR = "Job Posting Fetch Error",
  WISE_CREATE_RECIPIENT = "Wise Create Recipient Error",
  WISE_DELETE_RECIPIENT = "Wise Delete Recipient Error",
  CLIENT_STATUS_FETCH_ERROR = "Client Status Fetch Error",
  JOB_APPLICATION_FETCH_ERROR = "Job Application Fetch Error",
}
